# -*- coding: utf-8 -*-
"""ASF_Alter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HK2Dl5KeklL9T9GeWF-KT7BnpJdVvPSD
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
import os

# Set random seed
tf.random.set_seed(42)

# Dataset paths
train_dir = "/content/drive/Othercomputers/My Laptop/Educational/Sem-VI/INT345/Project/Fiber.v2i.folder/train"
valid_dir = "/content/drive/Othercomputers/My Laptop/Educational/Sem-VI/INT345/Project/Fiber.v2i.folder/valid"

# Model parameters
img_size = (224, 224)
batch_size = 64

# Data generators
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=45,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.3,
    zoom_range=0.3,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='reflect'
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True
)

validation_generator = val_datagen.flow_from_directory(
    valid_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical'
)

# Class weights
class_weights = compute_class_weight('balanced',
                                   classes=np.unique(train_generator.classes),
                                   y=train_generator.classes)
class_weights = dict(enumerate(class_weights))

# Build model
def build_model():
    base_model = MobileNetV2(
        input_shape=(*img_size, 3),
        include_top=False,
        weights='imagenet',
        alpha=0.35
    )
    base_model.trainable = False

    inputs = tf.keras.Input(shape=(*img_size, 3))
    x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
    x = base_model(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.7)(x)
    outputs = layers.Dense(3, activation='softmax')(x)

    return tf.keras.Model(inputs, outputs)

# Compile model
model = build_model()
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Callbacks
os.makedirs('model_checkpoints', exist_ok=True)
checkpoint_path = 'model_checkpoints/best_model.keras'
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=10, restore_best_weights=True),
    ModelCheckpoint(checkpoint_path, monitor='val_accuracy', save_best_only=True)
]

# Train model
history = model.fit(
    train_generator,
    epochs=100,
    validation_data=validation_generator,
    callbacks=callbacks,
    class_weight=class_weights
)

# Plot results
plt.figure(figsize=(15, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title('Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title('Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

# Save final model
model.save('fiber_classifier.keras')
print("Training complete. Model saved as 'fiber_classifier.keras'")

from tensorflow.keras.models import load_model
from sklearn.metrics import classification_report
import numpy as np

# Load model
model = load_model('fiber_classifier.keras')

# Prepare test data
test_dir = "/content/drive/Othercomputers/My Laptop/Educational/Sem-VI/INT345/Project/Fiber.v2i.folder/test"
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=8,
    class_mode='categorical',
    shuffle=False
)

# Evaluate
test_loss, test_acc = model.evaluate(test_generator)
print(f"\nTest Accuracy: {test_acc*100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# Generate predictions
test_generator.reset()
y_pred = model.predict(test_generator)
y_pred_classes = np.argmax(y_pred, axis=1)

# Classification report
print("\nClassification Report:")
print(classification_report(
    test_generator.classes,
    y_pred_classes,
    target_names=list(test_generator.class_indices.keys()),
    digits=4
))